{% set version = "2.26" %}

package:
  name: fossil-split
  version: {{ version }}

source:
  - url: https://fossil-scm.org/home/tarball/version-{{ version }}/fossil-src-{{ version }}.tar.gz
    sha256: a9be104c8055ada40985a158392d73f3c84829accb5b5d404e361fea360774c2

build:
  number: 0

outputs:
  - name: fossil
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-fossil.sh   # [unix]
        - call {{ RECIPE_DIR }}\build-fossil.bat  # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - ccache  # [unix]
        - emsdk   # [unix]
        - make    # [unix]
        - cmake   # [win]
        - perl    # [win]
      host:
        - openssl
        - tk
        - zlib
        - sqlite  # [unix]
    test:
      commands:
        - fossil --help

  - name: fossil-pikchr
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-pikchr.sh   # [unix]
        - call {{ RECIPE_DIR }}\build-pikchr.bat  # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}        # [unix]
        - {{ compiler("m2w64_c") }}  # [win]
      run_constrained:
        - {{ pin_subpackage("fossil", max_pin="x.x.x") }}
    test:
      files:
        - test.pikchr
      commands:
        - pikchr --svg-only test.pikchr
    about:
      home: https://pikchr.org
      license: 0BSD
      license_file: LICENSE-0BSD
      summary: Pikchr (pronounced "picture") is a PIC-like markup language for diagrams in technical documentation.

about:
  home: https://fossil-scm.org
  license: BSD-2-Clause
  license_file:
    - COPYRIGHT-BSD2.txt
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration management system with these advanced features:
  doc_url: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html
  dev_url: https://fossil-scm.org/index.html/dir?ci=tip

extra:
  feedstock-name: fossil
  recipe-maintainers:
    - bollwyvl
