{% set version = "2.22" %}

package:
  name: fossil-split
  version: {{ version }}

source:
  - url: https://fossil-scm.org/home/tarball/version-{{ version }}/fossil-src-{{ version }}.tar.gz
    sha256: b90c40beb75308b0eba46b5add6e54a7a9e65ac90ce86ec8d78ae2a4bb8bae60
  - url: https://spdx.org/licenses/0BSD.html
    sha256: f5c185366c65ec8ead22f9708e09e419aa5b7aec75ec321693030209b972b6df

build:
  number: 0

outputs:
  - name: fossil
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-fossil.sh  # [unix]
        - call {{ RECIPE_DIR }}\build-fossil.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - ccache  # [unix]
        - cmake  # [win]
        - emsdk  # [unix]
        - make  # [unix]
        - perl  # [win]
      host:
        - openssl
        - sqlite  # [unix]
        - tk
        - zlib
    test:
      commands:
        - fossil --help

  - name: fossil-pikchr
    build:
      script:
        - bash {{ RECIPE_DIR }}/build-pikchr.sh  # [unix]
        - call {{ RECIPE_DIR }}\build-pikchr.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
      run_constrained:
        - {{ pin_subpackage('fossil', max_pin='x.x.x') }}
    test:
      files:
        - test.pikchr
      commands:
        - pikchr --svg-only test.pikchr
    about:
      home: https://pikchr.org
      license: 0BSD
      license_file:
        - 0BSD.html
      summary: Pikchr (pronounced "picture") is a PIC-like markup language for diagrams in technical documentation.

about:
  home: https://fossil-scm.org
  license: BSD-2-Clause
  license_file:
    - COPYRIGHT-BSD2.txt
    - 0BSD.html
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration management system with these advanced features:
  doc_url: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html
  dev_url: https://fossil-scm.org/index.html/dir?ci=tip

extra:
  feedstock-name: fossil
  recipe-maintainers:
    - bollwyvl
