# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.26"
  python_min: "3.9"
  # test against some _other_ python
  python_check_max: "3.13"

recipe:
  name: fossil-split
  version: ${{ version }}

source:
  - if: osx
    then:
      # remove after https://github.com/prefix-dev/rattler-build/issues/1608
      - url: https://github.com/drhsqlite/fossil-mirror/archive/refs/tags/version-${{ version }}.tar.gz
        sha256: c4cf187324d8052896cc143d22e7c870b5c97719e89c3d94fc431912b8b40bb4
    else:
      - url: https://fossil-scm.org/home/tarball/version-${{ version }}/fossil-src-${{ version }}.tar.gz
        sha256: a9be104c8055ada40985a158392d73f3c84829accb5b5d404e361fea360774c2

build:
  number: 0
  # only build for the minimal python version
  skip: not (match(python, python_min ~ '.*'))

outputs:
  - package:
      name: fossil
    build:
      script:
        file: build-fossil
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - if: unix
          then:
            - ccache
            - emsdk
            - make
            - python
          else:
            - cmake
            - perl
      host:
        - openssl
        - tk
        - zlib
        - if: unix
          then:
            - sqlite
      ignore_run_exports:
        from_package:
          - python
          - python_abi
    tests:
      - script: fossil --help
      - requirements:
          run:
            # verify against some other python than the one we built with
            - python ${{ python_check_max }}.*
        script: fossil --help

  - package:
      name: fossil-pikchr
    build:
      script:
        file: build-pikchr
    requirements:
      build:
        - ${{ stdlib("c") }}
        - if: unix
          then: ${{ compiler("c") }}
          else: ${{ compiler("m2w64_c") }}
      run_constraints:
        - ${{ pin_subpackage("fossil", upper_bound="x.x.x") }}
    tests:
      - files:
          recipe:
            - test.pikchr
        requirements:
          run:
            - python ${{ python_check_max }}.*
        script:
          - pikchr --svg-only test.pikchr
    about:
      license: 0BSD
      license_file: LICENSE-0BSD
      summary: Pikchr (pronounced "picture") is a PIC-like markup language for diagrams in technical documentation.
      homepage: https://pikchr.org

about:
  license: BSD-2-Clause
  license_file:
    - COPYRIGHT-BSD2.txt
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration management system with these advanced features:
  homepage: https://fossil-scm.org
  repository: https://fossil-scm.org/index.html/dir?ci=tip
  documentation: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html

extra:
  feedstock-name: fossil
  recipe-maintainers:
    - bollwyvl
